---
- name: create license
  template:
    src: "templates/license.j2"
    dest: "/tmp/ucs.license"
  tags: license

- name: install ucs license
  shell:
    cmd: univention-license-import /tmp/ucs.license && univention-license-check
    executable: /bin/sh
  tags: license

- name: wait until uuid/license is defined in ucr
  wait_for:
    path: /etc/univention/base.conf
    search_regex: uuid/license
  tags: license
